// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import LanguageSwitcher from './components/LanguageSwitcher';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SWD Frontend Test',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
      <body className={inter.className}>
        <Providers>  {/* เปิด Provider ตรงนี้ */}
          <div style={{ position: 'relative', minHeight: '100vh' }}>
            {/* Language Switcher ขวาบน */}
            <div
              style={{
                position: 'absolute',
                top: 24,
                right: 24,
                zIndex: 1000,
              }}
            >
              <LanguageSwitcher />
            </div>

            {/* ทุกหน้าจะอยู่ข้างใน Provider แล้ว */}
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}